name: Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  checks:
    name: Run Checks
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4
      - name: Mark the directory as safe for git
        run: git config --global --add safe.directory $PWD
      - name: Install RPM dependencies
        run: |
          dnf install -y krb5-devel libpq-devel gettext python-tox poetry
      - name: Run tests
        run: tox -e ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env:
          - py38
          - py39
          - py310
          - py311
          - py312
          - format
          - lint
    runs-on: ubuntu-latest